### ISSUE TITLE
making the pdf

### ISSUE THREAD

**Issue by sje30** [ypriverol/github-paper#119]
This is probably a "meta issue" as it is not about your paper content, but the mechanics of making the paper.  README says:

    Then include the text from manuscript.tex (ignore title, authors and references) into manuscript-plos.tex.

This sounds like a copy/paste operation, which we all know is a no-no for making reproducible papers! 

Would you consider a patch to do this with a couple of unix commands?

**Comment by lgatto** [comment]
This was a case where manual was a short term time gain, even though it was not the right thing to do. Ideally, I would have used [rticles](https://github.com/rstudio/rticles), but at that time there was a problem with the PLoS template and I hadn't time to spare. 

Patch more than welcome!

**Comment by sje30** [comment]
I see.
Although using rticles is nice, it then assumes others will be in the R universe to recompile the paper.  

Wouldn't it be enough to do

    \input manuscript

within the manuscript-plos.tex file (which then has all the author information)?

Although why is `ack.md` in a separate file?

**Comment by lgatto** [comment]
> Although why is ack.md in a separate file?

Just to separate them from the main text. I think we will need to change this anyway as PLoS want to input funding at submission and Acknowledgements for personal thanks.

**Comment by lgatto** [comment]
> Wouldn't it be enough to do
>```
> \input manuscript
> ```

Probably, yes.

**Comment by alex-konovalov** [comment]
I am working on this now and discovered a missing file:
```
LaTeX Warning: File `PLOS-submission.eps' not found on input line 191.

! LaTeX Error: File `PLOS-submission.eps' not found.
```
Shall I comment it out, or could someone commit it please?

**Comment by lgatto** [comment]
I am also looking into this. Just adding an `\include manuscript` is not enough.
I am going to add the missing file in a minute.

**Comment by alex-konovalov** [comment]
We have list of authors in manuscript-plos.tex and the new one in manuscript.md. The LaTeX code for the header generated in manuscript.tex looks differently, and it seems that one should use the header from manuscript-plos.tex which is what PLOS requires. Is this the case?

If so, we might need to remove the header manuscript.md and keep it only in one place (manuscript-plos.tex)...

**Comment by lgatto** [comment]
Yes @ypriverol, this was and still is the case. The author list will probably still change, anyway.

**Comment by lgatto** [comment]
There are problems with the tables:
1. missing LaTeX packages: 
```
\usepackage{longtable}
\usepackage{booktabs}
```
2. Second table is completely broken (not interpreted as LaTeX at all) - may be due to another missing package.

**Comment by alex-konovalov** [comment]
Also this:
```! LaTeX Error: Cannot determine size of graphic in ./figure01_overview.pdf (no BoundingBox).

l.293 \includegraphics{./figure01_overview.pdf}
```

**Comment by lgatto** [comment]
@alex-konovalov we must anyway remove the figure from the source of the manuscript for submission (see note about commenting the `\includegraphics` in the REAMDE file).

**Comment by alex-konovalov** [comment]
@lgatto most amazingly, if you will copy table 1 instead table 2, you have the same problem. And if you will swap table 2 and table 1, everything builds fine.

**Comment by lgatto** [comment]
@alex-konovalov it is fixed now adding a newline (double space) between the tables, so that pandoc interprets the two tables as two `longtable` environments. 

Still now perfect, as the tables a too large for the page and the caption are simple text, rather than proper captions.

**Comment by alex-konovalov** [comment]
Great. At least now it looks like we are close to the state of building pdf automatically, and achieving this will help us to polish the final submission. When we will see PDF, it will be easier to see how we may compress tables. One of ideas for the table with the list of projects hosted on github is that they all have common prefix `https://github.com/`. If you can hide it, but make the remaining path a hyperlink, that would be helpful. In the table with links to teaching materials, the text in some cells in the 1st column could be written in 2 lines (need to see, may look ugly). BTW, the title of that table should say "Git for scientists" instead of "Git for scientist".

**Comment by lgatto** [comment]
or may be the easiest is to rotate them

**Comment by lgatto** [comment]
Closing this issue, as `make manuscript-plot.pdf` works as expected, and now a commit will trigger the pdf to be build (rather than only `manuscript.tex`). 

Please read the update README for instructions on what to modify - biggest change is that title and authors **must** be updated in `manuscript-plos.tex` following the syntax. 

Note that tables are still out overflowing.

**Comment by lgatto** [comment]
Tables are now sideways, using the `rotating` package (I hope that adding additional packages won't cause issues on the PLoS side). Not perfect yet, but at least we can read most of the content.
