### ISSUE TITLE
New rule - what/how git/github

### ISSUE THREAD

**Issue by lgatto** [ypriverol/github-paper#80]
I have had a go at a first rule that should give newcomers an idea of what git/github are and how to use them - https://github.com/lgatto/github-paper

I haven't sent a PR yet as it needs more work and more changes in later rules (what is now rule 2 for example) will be required.

**Comment by ypriverol** [comment]
@laurent I just take a look to it and looks really a good because it is an easy way to start. Timo and my self have been talking about the experience of writing a manuscript using github and the interaction we are planning to promote with the reviewers. Perhaps we should highlight that because it should be one of the first examples of this type of use in research.

**Comment by lgatto** [comment]
See this paragraph at the end of the *issues* rule:

> As another illustration of issues and their generic and wide application, we (https://github.com/ypriverol/github-paper/issues) and others (https://github.com/ropensci/RNeXML/issues/121) used GitHub issues to discuss and comment changes in manuscript and address reviewers' comments.

**Comment by ypriverol** [comment]
Great
